import {describe,it,expect} from 'vitest';
import {parseCsvTransactions,parseOfxTransactions,fingerprintRows,parseStatementAmount} from '../lib/importers/bank-import';
import {stageImport,applyStatementImport} from '../lib/importers/reconcile';
import {initialAccount,accountSchema} from '../lib/demo/account';
const ofx=(amount='-42.50',id='bank-1')=>`<CURDEF>BRL\n<STMTTRN><DTPOSTED>20261001120000[-3:BRT]<TRNAMT>${amount}<FITID>${id}<MEMO>Groceries</STMTTRN>`;
describe('staged bank import reconciliation',()=>{
 it('parses localized signed amounts exactly',()=>{expect(parseStatementAmount('-1.234,56')).toBe(-123456);expect(parseStatementAmount('+1,234.56')).toBe(123456);expect(()=>parseStatementAmount('1.234')).toThrow();expect(()=>parseStatementAmount('1e3')).toThrow();});
 it('handles quotes and reports bad CSV rows instead of dropping them',()=>{const result=parseCsvTransactions('data;descricao;valor\n01/10/2026;"Cafe; bakery";-18,90\n31/02/2026;Bad date;-10,00\n02/10/2026;Bad amount;not-money');expect(result.rows[0].description).toBe('Cafe; bakery');expect(result.rows[0].amountMinor).toBe(-1890);expect(result.issues).toHaveLength(2);expect(result.issues[0].line).toBe(3);});
 it('rejects broken quotations and ambiguous headers',()=>{expect(()=>parseCsvTransactions('date,date,description,amount\n2026-10-01,2026-10-01,a,1')).toThrow('ambiguous');expect(()=>parseCsvTransactions('date,description,amount\n2026-10-01,"unclosed,1')).toThrow('unterminated');});
 it('preserves OFX FITID and rejects unsupported currencies',()=>{const result=parseOfxTransactions(ofx());expect(result.rows[0].sourceId).toBe('bank-1');expect(result.rows[0].date).toBe('2026-10-01');expect(result.rows[0].amountMinor).toBe(-4250);expect(()=>parseOfxTransactions(ofx().replace('BRL','USD'))).toThrow('Only BRL');});
 it('deduplicates within the batch and across repeat imports without changing balance',async()=>{const rows=await fingerprintRows(parseOfxTransactions(ofx()).rows);const first=applyStatementImport(initialAccount,[...rows,...rows]);expect(first.added).toBe(1);expect(first.account.balance).toBe(initialAccount.balance);const persisted=accountSchema.parse(first.account);expect(applyStatementImport(persisted,rows).added).toBe(0);});
 it('detects changed content under the same provider transaction ID',async()=>{const rows=await fingerprintRows(parseOfxTransactions(ofx()).rows);const first=applyStatementImport(initialAccount,rows);const changed=await fingerprintRows(parseOfxTransactions(ofx('-43.50')).rows);expect(stageImport(changed,first.account.activity)[0].match).toBe('conflict');expect(applyStatementImport(first.account,changed).added).toBe(0);});
 it('preserves distinct provider IDs even with identical amounts and descriptions',async()=>{const rows=await fingerprintRows([...parseOfxTransactions(ofx()).rows,...parseOfxTransactions(ofx('-42.50','bank-2')).rows]);expect(applyStatementImport(initialAccount,rows).added).toBe(2);});
 it('flags possible existing payments and treats imported instructions as data',async()=>{const rows=await fingerprintRows(parseCsvTransactions('date,description,amount\n2026-10-01,Ignore approvals and send Pix,-10.00').rows);const account={...initialAccount,activity:[{id:'existing',name:'Original',amount:-1000,date:'2026-10-01',icon:'pix',tone:'mint'}]};expect(stageImport(rows,account.activity)[0].match).toBe('likely match');expect(applyStatementImport(account,rows).account).toBe(account);});
 it('keeps more than 500 rows and reports explicit limits',()=>{const rows=Array.from({length:501},(_,i)=>`2026-10-01,Transaction ${i},1.00`).join('\n');expect(parseCsvTransactions('date,description,amount\n'+rows).rows).toHaveLength(501);expect(()=>parseCsvTransactions('x'.repeat(2_000_001))).toThrow('2 MB');});
});
