import {describe,it,expect} from 'vitest';
import {toMinorUnits,fromMinorUnits} from '../lib/money/minorUnits';
import {canonicalRequest,requestFingerprint} from '../lib/idempotency/fingerprint';
import {calculateAffordability} from '../lib/finance/affordability';
import {assertReadOnlyTool} from '../lib/security/policy';
import {validateBalanced} from '../lib/finance/ledger';
describe('consolidated core hardening',()=>{
 it('round-trips signed integer money and handles zero-decimal currencies',()=>{expect(toMinorUnits('-123.45','BRL')).toBe(-12345n);expect(fromMinorUnits(-12345n,'BRL')).toBe('-123.45');expect(toMinorUnits('100','JPY')).toBe(100n);expect(fromMinorUnits(100n,'JPY')).toBe('100');});
 it('rejects unsupported precision instead of truncating or rounding',()=>{for(const value of ['1.001','NaN','Infinity','1e3','1.2.3',''])expect(()=>toMinorUnits(value,'BRL')).toThrow();expect(()=>toMinorUnits('1.0','JPY')).toThrow();expect(()=>toMinorUnits('1','XYZ' as never)).toThrow();});
 it('canonicalizes nested keys while preserving arrays and nested values',async()=>{const first={amount:100,recipient:{key:'a',name:'Maria'},tags:['one','two']};expect(await requestFingerprint(first)).toBe(await requestFingerprint({tags:['one','two'],recipient:{name:'Maria',key:'a'},amount:100}));expect(await requestFingerprint(first)).not.toBe(await requestFingerprint({...first,recipient:{key:'b',name:'Maria'}}));expect(await requestFingerprint(first)).not.toBe(await requestFingerprint({...first,tags:['two','one']}));});
 it('rejects ambiguous non-JSON requests and accessors without invoking them',()=>{const circular:{self?:unknown}={};circular.self=circular;for(const value of [{a:undefined},{a:NaN},new Date(),circular,Array(1)])expect(()=>canonicalRequest(value)).toThrow();const object={get amount(){throw new Error('getter invoked');}};expect(()=>canonicalRequest(object)).toThrow('accessors');});
 it('keeps affordability in integer units and rejects negative/non-finite inputs',()=>{const result=calculateAffordability({availableMinor:100000,proposedMinor:20000,unpaidBillsMinor:[10000,5000]});expect(result.safeToSpendMinor).toBe(50000);expect(result.canAfford).toBe(true);expect(()=>calculateAffordability({availableMinor:1000,proposedMinor:-1,unpaidBillsMinor:[]})).toThrow();expect(()=>calculateAffordability({availableMinor:Infinity,proposedMinor:1,unpaidBillsMinor:[]})).toThrow();});
 it('rejects money-moving tools at the read-only AI boundary',()=>{expect(()=>assertReadOnlyTool('pix.send')).toThrow();expect(()=>assertReadOnlyTool('bill.pay')).toThrow();expect(()=>assertReadOnlyTool('financial.snapshot')).not.toThrow();});
 it('rejects zero or overflowing ledger postings and missing identifiers',()=>{const command={commandId:'c',idempotencyKey:'k',postings:[{accountId:'a',amountMinor:100n,currency:'BRL' as const},{accountId:'b',amountMinor:-100n,currency:'BRL' as const}]};expect(()=>validateBalanced({...command,commandId:''})).toThrow();expect(()=>validateBalanced({...command,postings:command.postings.map(p=>({...p,amountMinor:0n}))})).toThrow();expect(()=>validateBalanced({...command,postings:command.postings.map(p=>({...p,accountId:' '}))})).toThrow();expect(()=>validateBalanced({...command,postings:command.postings.map(p=>({...p,amountMinor:p.amountMinor*1000000000000000000n}))})).toThrow();});
});
