'use client';
import {useRef,useState} from 'react';
import Link from 'next/link';
import {useAccount,updateAccount} from '../lib/demo/store';
import {parseMinor,type Transaction} from '../lib/demo/account';
import {recordExpense} from '../lib/demo/extensions';
import {Receipt,money} from './dialog';
export default function ExpenseImport(){
 const {activity}=useAccount();const file=useRef<HTMLInputElement>(null),command=useRef('');const [filename,setFilename]=useState(''),[merchant,setMerchant]=useState(''),[amount,setAmount]=useState(''),[category,setCategory]=useState('Food'),[date,setDate]=useState(()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})),[error,setError]=useState(''),[receipt,setReceipt]=useState<Transaction|null>(null),[confirm,setConfirm]=useState(false);
 function save(){try{const value=parseMinor(amount);if(!command.current)command.current=crypto.randomUUID();const next=updateAccount(a=>recordExpense(a,{id:command.current,merchant,amount:value,category,date,filename}));setReceipt(next.activity.find(t=>t.id===command.current)||null);setMerchant('');setAmount('');setFilename('');command.current='';if(file.current)file.current.value='';setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to record.');}}
 return <section className="panel page-panel"><h3>Receipts & expenses</h3><p className="page-subtitle">Choose a receipt and enter its details. Recorded expenses appear in Activity; your wallet balance stays unchanged.</p><button className="secondary" onClick={()=>file.current?.click()}>Choose receipt (optional)</button><input ref={file} type="file" accept="image/png,image/jpeg,application/pdf" hidden onChange={e=>{const selected=e.target.files?.[0];if(!selected)return;if(selected.size>10_000_000){setError('Choose a receipt smaller than 10 MB.');e.target.value='';return;}setFilename(selected.name);setError('');}}/>{filename&&<p className="privacy-note">{filename} · name recorded only. File contents are not uploaded or retained.</p>}<form onSubmit={e=>{e.preventDefault();save();}}><label className="field">Merchant<input value={merchant} onChange={e=>setMerchant(e.target.value)} maxLength={100}/></label><label className="field">Expense amount (BRL)<input value={amount} inputMode="decimal" onChange={e=>setAmount(e.target.value)}/></label><label className="field">Expense date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['Housing','Food','Transport','Subscriptions','Health','Shopping','Other'].map(c=><option key={c}>{c}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary">Record expense</button></form><Link className="secondary" href="/import/">Import a bank statement</Link><h3>Recorded expenses</h3>{activity.filter(t=>t.kind==='Recorded expense').map(t=><button className="saved-expense" key={t.id} onClick={()=>{setReceipt(t);setConfirm(false);}}><span><strong>{t.name}</strong><small>{t.category} · {t.date}</small></span><b>{money(Math.abs(t.amount))}</b></button>)}{receipt&&<Receipt transaction={receipt} close={()=>{setReceipt(null);setConfirm(false);}} actions={<><button className="danger-button" onClick={()=>setConfirm(true)}>Delete expense record</button>{confirm&&<div className="approval"><p>Delete this expense record? Your wallet balance stays unchanged.</p><button className="danger-button" onClick={()=>{try{updateAccount(a=>({...a,activity:a.activity.filter(t=>t.id!==receipt.id||t.kind!=='Recorded expense')}));setReceipt(null);setConfirm(false);}catch(e){setError(e instanceof Error?e.message:'Unable to delete.');}}}>Confirm delete expense</button></div>}</>}/>}</section>;
}
