'use client';
import {useState} from 'react';
import {useAccount,updateAccount} from '../lib/demo/store';
import {parseMinor} from '../lib/demo/account';
import {trackedSavings} from '../lib/demo/extensions';
import {Dialog,money} from './dialog';
export default function Goals(){
 const {goals}=useAccount();const [editing,setEditing]=useState<number|null>(null),[name,setName]=useState(''),[target,setTarget]=useState(''),[saved,setSaved]=useState('0'),[error,setError]=useState(''),[remove,setRemove]=useState(false);
 function open(index:number){const goal=goals[index];setEditing(index);setName(goal?.name||'');setTarget(goal?(goal.amount/100).toFixed(2):'');setSaved(goal?(goal.saved/100).toFixed(2):'0');setRemove(false);setError('');}
 function save(){try{const amount=parseMinor(target),progress=trackedSavings(saved);if(!name.trim())throw new Error('Enter a goal name.');if(progress>amount)throw new Error('Tracked savings cannot exceed the target.');updateAccount(a=>({...a,goals:editing===a.goals.length?[...a.goals,{name:name.trim(),amount,saved:progress}]:a.goals.map((g,i)=>i===editing?{name:name.trim(),amount,saved:progress}:g)}));setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}}
 return <section className="panel page-panel fluxo-goals-page"><div className="fluxo-screen-kicker">SAVINGS · FUTURE</div><h2>Savings Goals</h2><div className="fluxo-feature-banner"><span>YOUR NEXT MILESTONE</span><strong>Build towards what matters.</strong><small>Track your progress locally. No funds move.</small></div><h3>Your goals</h3><p className="page-subtitle">Track savings on this device. Updating a goal does not transfer money.</p>{goals.length===0&&<p className="empty">Create your first savings goal.</p>}{goals.map((g,i)=><div className="budget-row" key={i}><div><strong>{g.name}</strong><span>{money(g.saved)} / {money(g.amount)}</span></div><div className="progress"><i style={{width:`${Math.min(100,g.saved/g.amount*100)}%`}}/></div><small>{Math.round(g.saved/g.amount*100)}% tracked</small><button className="secondary" onClick={()=>open(i)}>Edit {g.name}</button></div>)}<button className="primary" onClick={()=>open(goals.length)}>Create a goal</button>{editing!==null&&<Dialog title={editing===goals.length?'Create goal':'Edit goal'} close={()=>setEditing(null)}><form onSubmit={e=>{e.preventDefault();save();}}><label className="field">Goal name<input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><label className="field">Target (BRL)<input value={target} inputMode="decimal" onChange={e=>setTarget(e.target.value)}/></label><label className="field">Tracked savings (BRL)<input value={saved} inputMode="decimal" onChange={e=>setSaved(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary">Save goal</button></form>{editing<goals.length&&<><button className="danger-button" onClick={()=>setRemove(true)}>Delete goal</button>{remove&&<div className="approval"><p>Delete this goal and its tracked progress?</p><button className="danger-button" onClick={()=>{try{updateAccount(a=>({...a,goals:a.goals.filter((_,i)=>i!==editing)}));setEditing(null);}catch(e){setError(e instanceof Error?e.message:'Unable to delete.');}}}>Confirm delete goal</button></div>}</>}</Dialog>}</section>;
}
